### ISSUE TITLE
Incorrect error when ServiceNow is sleeping mode

### ISSUE THREAD

**Issue by ienroll** [FXinnovation/alertmanager-webhook-servicenow#23]
When the ServiceNow in sleeping mode, webhook throws following error:
ERRO[0583] Error managing incident from alert : invalid character '<' looking for beginning of value  source="main.go:96"

Can this fixed so it that it actually say "ServiceNow" not available?

**Comment by louisfelix** [comment]
Hi @ienroll, I'll do some tests to reproduce this issue, thanks for sharing.
