### ISSUE TITLE
Use URL instead of instance name

### ISSUE THREAD

**Issue by jjLudin** [FXinnovation/alertmanager-webhook-servicenow#28]
Hi,

Is it possible to use a URL instead of an instance name? 

The ServiceNow API that I am trying to send requests to is using a URL like `https://instance_name.service-now.com/api/some/path`.

Thanks!

**Comment by louisfelix** [comment]
Hi,

This webhook is specifically meant to manage _incidents_ from AlertManager alerts.

It calls the [table API](https://developer.servicenow.com/app.do#!/rest_api_doc?v=madrid&id=r_TableAPI-GET) and specifically target the incident table (i.e.: api/now/v2/table/incident). As it is not meant to integrate generically with all the ServiceNow APIs, it's not possible to specify the complete API path.

Thanks!

**Comment by jjLudin** [comment]
I see. Thank you for your response. In this case, I will have to develop my own webhook since I am required to work with a complete API path. Closing the issue.
