### ISSUE TITLE
Build image fail relate to package github.com/prometheus/common/log is removed

### ISSUE THREAD

**Issue by chary1112004** [FXinnovation/alertmanager-webhook-servicenow#40]
Hi,

We are using to integrate from alertmanager to servicenow. It works before and now we are re-building image.
However, there is issue during building image like below:

1) Install certificate error
> go: gopkg.in/check.v1@v1.0.0-20190902080502-41f04d3bba15: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/7e5fa1eab4705eb80c[97](https://git.altemista.cloud/homologation/saas-devops/platform-template/basic-infrastructure/common/monitoring/alertmanager-webhook-servicenow/-/jobs/706632#L97)46632736cea906708d060702d529df6241d1c8c2c9f9: exit status 128:
	fatal: unable to access 'https://gopkg.in/check.v1/': server certificate verification failed. CAfile: none CRLfile: none
go: finding golang.org/x/sys v0.0.0-20200122134326-e047566fdf82
go: finding github.com/davecgh/go-spew v1.1.1
go: finding gopkg.in/alecthomas/kingpin.v2 v2.2.6
go: gopkg.in/alecthomas/kingpin.v2@v2.2.6: unknown revision v2.2.6
go: error loading module requirements
make: *** [Makefile:53: getpromu] Error 1

-> I am update Dockerfile to make it is downloaded certificate as below. 

> FROM golang:1.12 as builder
WORKDIR /alertmanager-webhook-servicenow/
COPY . .
RUN apt-get update
RUN apt-get install --reinstall ca-certificates
RUN make getpromu build

-> However it still have issue

> go: gopkg.in/alecthomas/kingpin.v2@v2.2.6: unknown revision v2.2.6
go: gopkg.in/yaml.v2@v2.2.8: unknown revision v2.2.8

2) Upgrade golang to 1.17
I upgrade golang to 1.17 as some suggestion as below

> FROM golang:1.17 as builder
WORKDIR /alertmanager-webhook-servicenow/
COPY . .
RUN apt-get update
RUN apt-get install --reinstall ca-certificates
RUN make getpromu build

However, it seems load lastest version of library and it could not download library is removed (github.com/prometheus/common/log)

> ...
go get: upgraded github.com/prometheus/common v0.9.1 => v0.32.1
...
main.go:23:2: no required module provides package github.com/prometheus/common/log; to add it:
	go get github.com/prometheus/common/log
!! command failed: build -o /alertmanager-webhook-servicenow/alertmanager-webhook-servicenow -ldflags -X github.com/prometheus/common/version.Version=1.4.0 -X github.com/prometheus/common/version.Revision=5e98ad17e74da81e50a0200de9edb438ba3af9b7 -X github.com/prometheus/common/version.Branch=HEAD -X github.com/prometheus/common/version.BuildUser=root@runner-qmewxuc2-project-4757-concurrent-0 -X github.com/prometheus/common/version.BuildDate=20220225-11:19:32  -extldflags '-static' -a -tags 'netgo static_build' github.com/FXinnovation/alertmanager-webhook-servicenow: exit status 1

Could you please support if I could resolve this issue?

Thanks a lot!

Regards,
Uyen Vu

**Comment by aarontavio** [comment]
Hi @chary1112004!

I could compile it by following these steps in docker:
```
git clone https://github.com/FXinnovation/alertmanager-webhook-servicenow.git
cd alertmanager-webhook-servicenow
docker run --rm -it -v $(pwd):/go/src golang:1.17
cd src
make getpromu
go get github.com/prometheus/common/log@v0.26.0
make build
```
So your Dockerfile should look like this I guess:

```
FROM golang:1.17 as builder
WORKDIR /alertmanager-webhook-servicenow/
COPY . .
RUN make getpromu
RUN go get github.com/prometheus/common/log@v0.26.0
RUN make build
```

I'm sure there is a more elegant way to do that, since I'm actually a java developer :D so if anybody has a better solution, please provide it. Anyways that should do the job.

**Comment by chary1112004** [comment]
Hi @aarontavio ,

thank you. Actually it works for me when I download latest code. However it does not work for current code.

Anyway, it works. Thanks for your information!

Regards,
Uyen Vu
